#!/bin/bash

# ===================================
# Script de Verificación de Formato
# ===================================
# Verifica que el código esté correctamente formateado
# y que pase todas las reglas de linting

set -e  # Exit on error

echo "🔍 Verificando formato y calidad de código..."
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Counters
ERRORS=0
WARNINGS=0

# ===================================
# 1. Verificar Prettier
# ===================================
echo "📝 Verificando formato con Prettier..."
if pnpm exec prettier --check . 2>/dev/null; then
    echo -e "${GREEN}✅ Prettier: Código correctamente formateado${NC}"
else
    echo -e "${RED}❌ Prettier: Código necesita formateo${NC}"
    echo ""
    echo "   Para arreglar automáticamente:"
    echo "   pnpm format"
    echo ""
    ((ERRORS++))
fi
echo ""

# ===================================
# 2. Verificar ESLint
# ===================================
echo "🔍 Verificando calidad con ESLint..."
if pnpm lint 2>/dev/null; then
    echo -e "${GREEN}✅ ESLint: Sin errores de linting${NC}"
else
    echo -e "${RED}❌ ESLint: Errores encontrados${NC}"
    echo ""
    echo "   Para arreglar automáticamente:"
    echo "   pnpm lint:fix"
    echo ""
    ((ERRORS++))
fi
echo ""

# ===================================
# 3. Verificar TypeScript
# ===================================
echo "🔷 Verificando tipos con TypeScript..."
if pnpm exec tsc --noEmit 2>/dev/null; then
    echo -e "${GREEN}✅ TypeScript: Sin errores de tipado${NC}"
else
    echo -e "${RED}❌ TypeScript: Errores de tipado encontrados${NC}"
    echo ""
    echo "   Revisa los errores arriba"
    echo ""
    ((ERRORS++))
fi
echo ""

# ===================================
# 4. Verificar archivos ignorados
# ===================================
echo "🚫 Verificando que archivos críticos no fueron modificados..."

# Verificar pnpm-lock.yaml
if git diff --quiet pnpm-lock.yaml 2>/dev/null; then
    echo -e "${GREEN}✅ pnpm-lock.yaml: Sin cambios${NC}"
else
    if [ -f pnpm-lock.yaml ]; then
        echo -e "${YELLOW}⚠️  pnpm-lock.yaml: Fue modificado${NC}"
        echo "   Esto es normal si agregaste/actualizaste dependencias"
        ((WARNINGS++))
    fi
fi

# Verificar payload-types.ts no tiene errores de formato
if [ -f src/payload-types.ts ]; then
    if grep -q "// This file is automatically generated" src/payload-types.ts 2>/dev/null; then
        echo -e "${GREEN}✅ payload-types.ts: Archivo generado correctamente${NC}"
    else
        echo -e "${YELLOW}⚠️  payload-types.ts: Puede necesitar regeneración${NC}"
        echo "   Ejecuta: pnpm generate:types"
        ((WARNINGS++))
    fi
fi

echo ""

# ===================================
# 5. Verificar que semicolons estén presentes
# ===================================
echo "🔍 Verificando uso de semicolons..."

# Contar archivos sin semicolon al final de declaraciones
MISSING_SEMICOLONS=0

# Buscar en archivos TypeScript/JavaScript
while IFS= read -r file; do
    # Ignorar archivos que deberían tener semicolons
    if [[ "$file" == *"node_modules"* ]] || \
       [[ "$file" == *".next"* ]] || \
       [[ "$file" == *"payload-types.ts"* ]]; then
        continue
    fi

    # Buscar líneas que parecen necesitar semicolon
    # (esto es una verificación simple, no exhaustiva)
    if grep -qE "(const|let|var|import|export).+[^;]$" "$file" 2>/dev/null; then
        ((MISSING_SEMICOLONS++))
    fi
done < <(find src -type f \( -name "*.ts" -o -name "*.tsx" \) 2>/dev/null || true)

if [ $MISSING_SEMICOLONS -eq 0 ]; then
    echo -e "${GREEN}✅ Semicolons: Correctamente usados${NC}"
else
    echo -e "${YELLOW}⚠️  Posibles semicolons faltantes en $MISSING_SEMICOLONS archivo(s)${NC}"
    echo "   Ejecuta 'pnpm format' para arreglar automáticamente"
    ((WARNINGS++))
fi

echo ""

# ===================================
# Resumen
# ===================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 RESUMEN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ $ERRORS -eq 0 ] && [ $WARNINGS -eq 0 ]; then
    echo -e "${GREEN}✨ ¡Todo perfecto! Código listo para commit${NC}"
    echo ""
    exit 0
elif [ $ERRORS -eq 0 ]; then
    echo -e "${YELLOW}⚠️  $WARNINGS advertencia(s) encontrada(s)${NC}"
    echo -e "${GREEN}✅ Sin errores - Código puede ser commiteado${NC}"
    echo ""
    exit 0
else
    echo -e "${RED}❌ $ERRORS error(es) encontrado(s)${NC}"
    if [ $WARNINGS -gt 0 ]; then
        echo -e "${YELLOW}⚠️  $WARNINGS advertencia(s) encontrada(s)${NC}"
    fi
    echo ""
    echo "🔧 Comandos para arreglar:"
    echo "   pnpm format      # Formatear código"
    echo "   pnpm lint:fix    # Fix linting automático"
    echo ""
    exit 1
fi
