#!/bin/bash

set -e

echo "Verificando formato y calidad de codigo"
echo ""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ERRORS=0
WARNINGS=0

echo "Verificando formato con Prettier"
if pnpm exec prettier --check . 2>/dev/null; then
    echo -e "${GREEN}Prettier: Codigo correctamente formateado${NC}"
else
    echo -e "${RED}Prettier: Codigo necesita formateo${NC}"
    echo ""
    echo "Para arreglar automaticamente:"
    echo "pnpm format"
    echo ""
    ((ERRORS++))
fi
echo ""

echo "Verificando calidad con ESLint"
if pnpm lint 2>/dev/null; then
    echo -e "${GREEN}ESLint: Sin errores de linting${NC}"
else
    echo -e "${RED}ESLint: Errores encontrados${NC}"
    echo ""
    echo "Para arreglar automaticamente:"
    echo "pnpm lint:fix"
    echo ""
    ((ERRORS++))
fi
echo ""

echo "Verificando tipos con TypeScript"
if pnpm exec tsc --noEmit 2>/dev/null; then
    echo -e "${GREEN}TypeScript: Sin errores de tipado${NC}"
else
    echo -e "${RED}TypeScript: Errores de tipado encontrados${NC}"
    echo ""
    ((ERRORS++))
fi
echo ""

echo "Verificando archivos criticos"
if git diff --quiet pnpm-lock.yaml 2>/dev/null; then
    echo -e "${GREEN}pnpm-lock.yaml: Sin cambios${NC}"
else
    if [ -f pnpm-lock.yaml ]; then
        echo -e "${YELLOW}pnpm-lock.yaml: Fue modificado${NC}"
        ((WARNINGS++))
    fi
fi

if [ -f src/payload-types.ts ]; then
    if grep -q "// This file is automatically generated" src/payload-types.ts 2>/dev/null; then
        echo -e "${GREEN}payload-types.ts: Archivo generado correctamente${NC}"
    else
        echo -e "${YELLOW}payload-types.ts: Puede necesitar regeneracion${NC}"
        echo "Ejecuta: pnpm generate:types"
        ((WARNINGS++))
    fi
fi

echo ""
echo "Verificando uso de semicolons"

MISSING_SEMICOLONS=0
while IFS= read -r file; do
    if [[ "$file" == *"node_modules"* ]] || [[ "$file" == *".next"* ]] || [[ "$file" == *"payload-types.ts"* ]]; then
        continue
    fi
    if grep -qE "(const|let|var|import|export).+[^;]$" "$file" 2>/dev/null; then
        ((MISSING_SEMICOLONS++))
    fi
done < <(find src -type f \( -name "*.ts" -o -name "*.tsx" \) 2>/dev/null || true)

if [ $MISSING_SEMICOLONS -eq 0 ]; then
    echo -e "${GREEN}Semicolons: Correctamente usados${NC}"
else
    echo -e "${YELLOW}Posibles semicolons faltantes en $MISSING_SEMICOLONS archivo(s)${NC}"
    echo "Ejecuta 'pnpm format' para arreglar automaticamente"
    ((WARNINGS++))
fi

echo ""
echo "RESUMEN"

if [ $ERRORS -eq 0 ] && [ $WARNINGS -eq 0 ]; then
    echo -e "${GREEN}Todo perfecto. Codigo listo para commit${NC}"
    exit 0
elif [ $ERRORS -eq 0 ]; then
    echo -e "${YELLOW}$WARNINGS advertencia(s) encontrada(s)${NC}"
    echo -e "${GREEN}Sin errores. Codigo puede ser commiteado${NC}"
    exit 0
else
    echo -e "${RED}$ERRORS error(es) encontrado(s)${NC}"
    if [ $WARNINGS -gt 0 ]; then
        echo -e "${YELLOW}$WARNINGS advertencia(s) encontrada(s)${NC}"
    fi
    echo ""
    echo "Comandos para arreglar:"
    echo "pnpm format"
    echo "pnpm lint:fix"
    exit 1
fi
